### ISSUE TITLE
Section on where to find help

### ISSUE THREAD

**Issue by GreatEmerald** [GeoScripting-WUR/Intro2Linux#2]
The next lesson, RProjectManagement, includes a nice section about where to find help when one is stuck with a programming task. I believe that would also be useful in the Linux lesson. The two overlap a bit (first step is usually to use a search engine in either case), but also have some differences.

In particular, distributions usually have wikis where most common issues are described. Otherwise, usual support channels are distribution IRC channels (most often simple questions are very quickly answered there, and there are convenient web interfaces to IRC) and distribution forums (for more complex questions). Ubuntu also has a Stack Exchange-like Q&A board called Ask Ubuntu. In some cases there are also mailing lists (albeit nowadays it's mostly relegated to talks between developers rather than users).

Another thing worth mentioning is what to do when one finds a bug: where and how to report it (also the importance of reporting bugs, so it gets fixed for everyone). In those cases the biggest challenge is to identify the piece of software the problem is in (can be tricky for those coming from Windows, since it's also all very monolithic unlike Linux), and whether it has already been reported. The distribution's bug tracker is usually the best starting point, the bug managers there usually redirect one to other bug trackers if the issue is not distribution-specific. Asking about where to file it on IRC is also a good option.

Perhaps it's also useful to note down and clarify the meaning of terms "upstream" and "downstream" somewhere, as it's relevant to both bugs and software projects on git in general.

I suppose this would be most clear in a paragraph, although a graph (perhaps also combining how to search for help in R projects as per the next lesson) might also be useful as an addition.

**Comment by janverbesselt** [comment]
Especially finding help is important for the students. I would say that bug report is more for experienced scripters, and should only be done if you have double checked with expert users. So writing about 'bug reporting' is not necessary in the context of 'geo-scripting'. You could mention it in a 'advanced' section or note for expert users.
